### ISSUE TITLE
Bug on breadcrumbs page

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#48]
After my presentation on a conference, someone managed to bring down KitchenSink by playing with BreadcrumbsPage.

I don't know the reason yet, but this is the exception in log:

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at KitchenSink.TreeItem.get_Name()
   at KitchenSink.BreadcrumbPage.SetActiveItem(TreeItem treeItem, Boolean isAdd) in C:\Users\Joozek\dev\KitchenSink\src\KitchenSink\BreadcrumbPage.json.cs:line 37
   at KitchenSink.BreadcrumbPageCurrentTreeItem.Handle(Save action) in C:\Users\Joozek\dev\KitchenSink\src\KitchenSink\BreadcrumbPage.json.cs:line 167
   at KitchenSink.BreadcrumbPageCurrentTreeItem.JsonByExample.Schema.<>c.<.ctor>b__0_9(Json pup, Input`1 input) in C:\Users\Joozek\dev\KitchenSink\src\KitchenSink\obj\x64\Debug\BreadcrumbPage.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 240
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 262
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 104
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter\TransactionManager.cs:line 454
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 34
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 678
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 519
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 56
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 288
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-316\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2147467261
"
```

**Comment by Mnosek** [comment]
Unfortunately I can't reproduce this bug by BreadcrumbsPage normal behaviour. The only way to call this error is to either edit root item (Products) or add a new root item. Both operations are unavailable at user level. Any idea?

**Comment by warpech** [comment]
Closing as not reproducible.
